# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


variables:
  agent.disablelogplugin.TestResultLogPlugin: 'false'
  skipComponentGovernanceDetection: 'true'
  imageRepository: 'test2'
  containerRegistry: 'dockerazure.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imgName: '$(containerRegistry)/$(imageRepository):$(tag)'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: windows-2019
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'dockerazure'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerazure'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - script: |
          docker run $(imgName)

